# name: "Build React"

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - master

# permissions:
#   contents: read
  
# # Todo: check if this is required  
# concurrency:
#   group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
#   cancel-in-progress: true
  
# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
    
#     - name: Setup node
#       uses: actions/setup-node@v3
#       with: 
#         node-version: 16.14.x
#         cache: npm
#         cache-dependency-path: frontend/package-lock.json
    
#     - name: Install packages
#       run: cd frontend && npm ci 
      
#     - name: Build react
#       env:
#         CI: false
#       run: |
#         cd frontend
#         npm run build
      
#     - name: Copy built static files to Azure VM
#       run: |
#         # chmod 400 credentials/gdsd1Restaurant.pem
#         # scp -r -i credentials/gdsd1Restaurant.pem -o StrictHostKeyChecking=no frontend/build/ stha24@gdsd1restaurant.westeurope.cloudapp.azure.com:/var/www/test/html


      
      
      
      
      
    
